// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/server/server.go

// Package server is a generated GoMock package.
package server

import (
	context "context"
	model "gophkeeper/internal/dto/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockStorage) CreateUser(ctx context.Context, user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStorageMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStorage)(nil).CreateUser), ctx, user)
}

// DeleteSecret mocks base method.
func (m *MockStorage) DeleteSecret(ctx context.Context, user, secretName, secretTYPE string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, user, secretName, secretTYPE)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockStorageMockRecorder) DeleteSecret(ctx, user, secretName, secretTYPE interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockStorage)(nil).DeleteSecret), ctx, user, secretName, secretTYPE)
}

// GetSecret mocks base method.
func (m *MockStorage) GetSecret(ctx context.Context, user, secretName, secretType string) (model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, user, secretName, secretType)
	ret0, _ := ret[0].(model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockStorageMockRecorder) GetSecret(ctx, user, secretName, secretType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockStorage)(nil).GetSecret), ctx, user, secretName, secretType)
}

// GetSecretList mocks base method.
func (m *MockStorage) GetSecretList(ctx context.Context, user string) ([]model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretList", ctx, user)
	ret0, _ := ret[0].([]model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretList indicates an expected call of GetSecretList.
func (mr *MockStorageMockRecorder) GetSecretList(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretList", reflect.TypeOf((*MockStorage)(nil).GetSecretList), ctx, user)
}

// GetSecretListInType mocks base method.
func (m *MockStorage) GetSecretListInType(ctx context.Context, user, secretType string) ([]model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretListInType", ctx, user, secretType)
	ret0, _ := ret[0].([]model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretListInType indicates an expected call of GetSecretListInType.
func (mr *MockStorageMockRecorder) GetSecretListInType(ctx, user, secretType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretListInType", reflect.TypeOf((*MockStorage)(nil).GetSecretListInType), ctx, user, secretType)
}

// GetUserHash mocks base method.
func (m *MockStorage) GetUserHash(ctx context.Context, login string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserHash", ctx, login)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserHash indicates an expected call of GetUserHash.
func (mr *MockStorageMockRecorder) GetUserHash(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserHash", reflect.TypeOf((*MockStorage)(nil).GetUserHash), ctx, login)
}

// SecretExists mocks base method.
func (m *MockStorage) SecretExists(ctx context.Context, user, secretName, typeSecret string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecretExists", ctx, user, secretName, typeSecret)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SecretExists indicates an expected call of SecretExists.
func (mr *MockStorageMockRecorder) SecretExists(ctx, user, secretName, typeSecret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecretExists", reflect.TypeOf((*MockStorage)(nil).SecretExists), ctx, user, secretName, typeSecret)
}

// UpdateSecret mocks base method.
func (m *MockStorage) UpdateSecret(ctx context.Context, user string, secret *model.Secret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, user, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockStorageMockRecorder) UpdateSecret(ctx, user, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockStorage)(nil).UpdateSecret), ctx, user, secret)
}

// UserExists mocks base method.
func (m *MockStorage) UserExists(ctx context.Context, login string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserExists", ctx, login)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserExists indicates an expected call of UserExists.
func (mr *MockStorageMockRecorder) UserExists(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserExists", reflect.TypeOf((*MockStorage)(nil).UserExists), ctx, login)
}

// СreateSecret mocks base method.
func (m *MockStorage) СreateSecret(ctx context.Context, user string, secret *model.Secret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "СreateSecret", ctx, user, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// СreateSecret indicates an expected call of СreateSecret.
func (mr *MockStorageMockRecorder) СreateSecret(ctx, user, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "СreateSecret", reflect.TypeOf((*MockStorage)(nil).СreateSecret), ctx, user, secret)
}

// MockJWTManager is a mock of JWTManager interface.
type MockJWTManager struct {
	ctrl     *gomock.Controller
	recorder *MockJWTManagerMockRecorder
}

// MockJWTManagerMockRecorder is the mock recorder for MockJWTManager.
type MockJWTManagerMockRecorder struct {
	mock *MockJWTManager
}

// NewMockJWTManager creates a new mock instance.
func NewMockJWTManager(ctrl *gomock.Controller) *MockJWTManager {
	mock := &MockJWTManager{ctrl: ctrl}
	mock.recorder = &MockJWTManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTManager) EXPECT() *MockJWTManagerMockRecorder {
	return m.recorder
}

// GetLoginFromToken mocks base method.
func (m *MockJWTManager) GetLoginFromToken(tokenString string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginFromToken", tokenString)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginFromToken indicates an expected call of GetLoginFromToken.
func (mr *MockJWTManagerMockRecorder) GetLoginFromToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginFromToken", reflect.TypeOf((*MockJWTManager)(nil).GetLoginFromToken), tokenString)
}

// IssueJWT mocks base method.
func (m *MockJWTManager) IssueJWT(user string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueJWT", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueJWT indicates an expected call of IssueJWT.
func (mr *MockJWTManagerMockRecorder) IssueJWT(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueJWT", reflect.TypeOf((*MockJWTManager)(nil).IssueJWT), user)
}
