// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/pkg/proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_SECRET_TYPE_UNSPECIFIED    SecretType = 0
	SecretType_SECRET_TYPE_LOGIN_PASSWORD SecretType = 1
	SecretType_SECRET_TYPE_TEXT           SecretType = 2
	SecretType_DSECRET_TYPE_BINARY        SecretType = 3
	SecretType_DSECRET_TYPE_CARD          SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_LOGIN_PASSWORD",
		2: "SECRET_TYPE_TEXT",
		3: "DSECRET_TYPE_BINARY",
		4: "DSECRET_TYPE_CARD",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED":    0,
		"SECRET_TYPE_LOGIN_PASSWORD": 1,
		"SECRET_TYPE_TEXT":           2,
		"DSECRET_TYPE_BINARY":        3,
		"DSECRET_TYPE_CARD":          4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pkg_proto_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_internal_pkg_proto_gophkeeper_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Secret struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretType    SecretType             `protobuf:"varint,1,opt,name=secret_type,json=secretType,proto3,enum=gophkeeper.SecretType"`
	xxx_hidden_Name          string                 `protobuf:"bytes,2,opt,name=name,proto3"`
	xxx_hidden_Description   string                 `protobuf:"bytes,3,opt,name=description,proto3"`
	xxx_hidden_EncryptedData []byte                 `protobuf:"bytes,4,opt,name=encrypted_data,json=encryptedData,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Secret) GetSecretType() SecretType {
	if x != nil {
		return x.xxx_hidden_SecretType
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Secret) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Secret) GetEncryptedData() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedData
	}
	return nil
}

func (x *Secret) SetSecretType(v SecretType) {
	x.xxx_hidden_SecretType = v
}

func (x *Secret) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Secret) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Secret) SetEncryptedData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedData = v
}

type Secret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretType    SecretType
	Name          string
	Description   string
	EncryptedData []byte
}

func (b0 Secret_builder) Build() *Secret {
	m0 := &Secret{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SecretType = b.SecretType
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_EncryptedData = b.EncryptedData
	return m0
}

type User struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login    string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *User) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *User) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    string
	Password string
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	return m0
}

type Token struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token string                 `protobuf:"bytes,1,opt,name=token,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *Token) SetToken(v string) {
	x.xxx_hidden_Token = v
}

type Token_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token string
}

func (b0 Token_builder) Build() *Token {
	m0 := &Token{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	return m0
}

type CreateSecretRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret *Secret                `protobuf:"bytes,1,opt,name=secret,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSecretRequest) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *CreateSecretRequest) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *CreateSecretRequest) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *CreateSecretRequest) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type CreateSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret *Secret
}

func (b0 CreateSecretRequest_builder) Build() *CreateSecretRequest {
	m0 := &CreateSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CreateSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CreateSecretResponse_builder) Build() *CreateSecretResponse {
	m0 := &CreateSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type UpdateSecretRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret *Secret                `protobuf:"bytes,1,opt,name=secret,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateSecretRequest) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *UpdateSecretRequest) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *UpdateSecretRequest) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *UpdateSecretRequest) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type UpdateSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret *Secret
}

func (b0 UpdateSecretRequest_builder) Build() *UpdateSecretRequest {
	m0 := &UpdateSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UpdateSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UpdateSecretResponse_builder) Build() *UpdateSecretResponse {
	m0 := &UpdateSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LoginRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User *User                  `protobuf:"bytes,1,opt,name=user,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *LoginRequest) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *LoginRequest) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *LoginRequest) ClearUser() {
	x.xxx_hidden_User = nil
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *User
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	return m0
}

type LoginResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token *Token                 `protobuf:"bytes,1,opt,name=token,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetToken() *Token {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return nil
}

func (x *LoginResponse) SetToken(v *Token) {
	x.xxx_hidden_Token = v
}

func (x *LoginResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Token != nil
}

func (x *LoginResponse) ClearToken() {
	x.xxx_hidden_Token = nil
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token *Token
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	return m0
}

type DeleteSecretRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretType SecretType             `protobuf:"varint,2,opt,name=secret_type,json=secretType,proto3,enum=gophkeeper.SecretType"`
	xxx_hidden_SecretName string                 `protobuf:"bytes,3,opt,name=secret_name,json=secretName,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSecretRequest) GetSecretType() SecretType {
	if x != nil {
		return x.xxx_hidden_SecretType
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *DeleteSecretRequest) GetSecretName() string {
	if x != nil {
		return x.xxx_hidden_SecretName
	}
	return ""
}

func (x *DeleteSecretRequest) SetSecretType(v SecretType) {
	x.xxx_hidden_SecretType = v
}

func (x *DeleteSecretRequest) SetSecretName(v string) {
	x.xxx_hidden_SecretName = v
}

type DeleteSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretType SecretType
	SecretName string
}

func (b0 DeleteSecretRequest_builder) Build() *DeleteSecretRequest {
	m0 := &DeleteSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SecretType = b.SecretType
	x.xxx_hidden_SecretName = b.SecretName
	return m0
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteSecretResponse_builder) Build() *DeleteSecretResponse {
	m0 := &DeleteSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetSecretRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretType SecretType             `protobuf:"varint,2,opt,name=secret_type,json=secretType,proto3,enum=gophkeeper.SecretType"`
	xxx_hidden_SecretName string                 `protobuf:"bytes,3,opt,name=secret_name,json=secretName,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretRequest) GetSecretType() SecretType {
	if x != nil {
		return x.xxx_hidden_SecretType
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *GetSecretRequest) GetSecretName() string {
	if x != nil {
		return x.xxx_hidden_SecretName
	}
	return ""
}

func (x *GetSecretRequest) SetSecretType(v SecretType) {
	x.xxx_hidden_SecretType = v
}

func (x *GetSecretRequest) SetSecretName(v string) {
	x.xxx_hidden_SecretName = v
}

type GetSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretType SecretType
	SecretName string
}

func (b0 GetSecretRequest_builder) Build() *GetSecretRequest {
	m0 := &GetSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SecretType = b.SecretType
	x.xxx_hidden_SecretName = b.SecretName
	return m0
}

type GetSecretResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret *Secret                `protobuf:"bytes,1,opt,name=secret,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *GetSecretResponse) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *GetSecretResponse) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *GetSecretResponse) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type GetSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret *Secret
}

func (b0 GetSecretResponse_builder) Build() *GetSecretResponse {
	m0 := &GetSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type GetListSecretsRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretType SecretType             `protobuf:"varint,1,opt,name=secret_type,json=secretType,proto3,enum=gophkeeper.SecretType"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetListSecretsRequest) Reset() {
	*x = GetListSecretsRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListSecretsRequest) ProtoMessage() {}

func (x *GetListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetListSecretsRequest) GetSecretType() SecretType {
	if x != nil {
		return x.xxx_hidden_SecretType
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *GetListSecretsRequest) SetSecretType(v SecretType) {
	x.xxx_hidden_SecretType = v
}

type GetListSecretsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretType SecretType
}

func (b0 GetListSecretsRequest_builder) Build() *GetListSecretsRequest {
	m0 := &GetListSecretsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SecretType = b.SecretType
	return m0
}

type GetListSecretsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets *[]*Secret             `protobuf:"bytes,1,rep,name=secrets,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetListSecretsResponse) Reset() {
	*x = GetListSecretsResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListSecretsResponse) ProtoMessage() {}

func (x *GetListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetListSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *GetListSecretsResponse) SetSecrets(v []*Secret) {
	x.xxx_hidden_Secrets = &v
}

type GetListSecretsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets []*Secret
}

func (b0 GetListSecretsResponse_builder) Build() *GetListSecretsResponse {
	m0 := &GetListSecretsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	return m0
}

var File_internal_pkg_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_internal_pkg_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"#internal/pkg/proto/gophkeeper.proto\x12\n" +
	"gophkeeper\"\x9e\x01\n" +
	"\x06Secret\x127\n" +
	"\vsecret_type\x18\x01 \x01(\x0e2\x16.gophkeeper.SecretTypeR\n" +
	"secretType\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0eencrypted_data\x18\x04 \x01(\fR\rencryptedData\"8\n" +
	"\x04User\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x1d\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"A\n" +
	"\x13CreateSecretRequest\x12*\n" +
	"\x06secret\x18\x01 \x01(\v2\x12.gophkeeper.SecretR\x06secret\"\x16\n" +
	"\x14CreateSecretResponse\"A\n" +
	"\x13UpdateSecretRequest\x12*\n" +
	"\x06secret\x18\x01 \x01(\v2\x12.gophkeeper.SecretR\x06secret\"\x16\n" +
	"\x14UpdateSecretResponse\"4\n" +
	"\fLoginRequest\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.gophkeeper.UserR\x04user\"8\n" +
	"\rLoginResponse\x12'\n" +
	"\x05token\x18\x01 \x01(\v2\x11.gophkeeper.TokenR\x05token\"o\n" +
	"\x13DeleteSecretRequest\x127\n" +
	"\vsecret_type\x18\x02 \x01(\x0e2\x16.gophkeeper.SecretTypeR\n" +
	"secretType\x12\x1f\n" +
	"\vsecret_name\x18\x03 \x01(\tR\n" +
	"secretName\"\x16\n" +
	"\x14DeleteSecretResponse\"l\n" +
	"\x10GetSecretRequest\x127\n" +
	"\vsecret_type\x18\x02 \x01(\x0e2\x16.gophkeeper.SecretTypeR\n" +
	"secretType\x12\x1f\n" +
	"\vsecret_name\x18\x03 \x01(\tR\n" +
	"secretName\"?\n" +
	"\x11GetSecretResponse\x12*\n" +
	"\x06secret\x18\x01 \x01(\v2\x12.gophkeeper.SecretR\x06secret\"P\n" +
	"\x15GetListSecretsRequest\x127\n" +
	"\vsecret_type\x18\x01 \x01(\x0e2\x16.gophkeeper.SecretTypeR\n" +
	"secretType\"F\n" +
	"\x16GetListSecretsResponse\x12,\n" +
	"\asecrets\x18\x01 \x03(\v2\x12.gophkeeper.SecretR\asecrets*\x8f\x01\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSECRET_TYPE_LOGIN_PASSWORD\x10\x01\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x02\x12\x17\n" +
	"\x13DSECRET_TYPE_BINARY\x10\x03\x12\x15\n" +
	"\x11DSECRET_TYPE_CARD\x10\x042\xa4\x04\n" +
	"\n" +
	"GophKeeper\x12?\n" +
	"\bRegister\x12\x18.gophkeeper.LoginRequest\x1a\x19.gophkeeper.LoginResponse\x12<\n" +
	"\x05Login\x12\x18.gophkeeper.LoginRequest\x1a\x19.gophkeeper.LoginResponse\x12Q\n" +
	"\fCreateSecret\x12\x1f.gophkeeper.CreateSecretRequest\x1a .gophkeeper.CreateSecretResponse\x12H\n" +
	"\tGetSecret\x12\x1c.gophkeeper.GetSecretRequest\x1a\x1d.gophkeeper.GetSecretResponse\x12T\n" +
	"\vListSecrets\x12!.gophkeeper.GetListSecretsRequest\x1a\".gophkeeper.GetListSecretsResponse\x12Q\n" +
	"\fUpdateSecret\x12\x1f.gophkeeper.UpdateSecretRequest\x1a .gophkeeper.UpdateSecretResponse\x12Q\n" +
	"\fDeleteSecret\x12\x1f.gophkeeper.DeleteSecretRequest\x1a .gophkeeper.DeleteSecretResponseB4Z2github.com/alegaliev/gophkeeper/internal/pkg/protob\x06proto3"

var file_internal_pkg_proto_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pkg_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_pkg_proto_gophkeeper_proto_goTypes = []any{
	(SecretType)(0),                // 0: gophkeeper.SecretType
	(*Secret)(nil),                 // 1: gophkeeper.Secret
	(*User)(nil),                   // 2: gophkeeper.User
	(*Token)(nil),                  // 3: gophkeeper.Token
	(*CreateSecretRequest)(nil),    // 4: gophkeeper.CreateSecretRequest
	(*CreateSecretResponse)(nil),   // 5: gophkeeper.CreateSecretResponse
	(*UpdateSecretRequest)(nil),    // 6: gophkeeper.UpdateSecretRequest
	(*UpdateSecretResponse)(nil),   // 7: gophkeeper.UpdateSecretResponse
	(*LoginRequest)(nil),           // 8: gophkeeper.LoginRequest
	(*LoginResponse)(nil),          // 9: gophkeeper.LoginResponse
	(*DeleteSecretRequest)(nil),    // 10: gophkeeper.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),   // 11: gophkeeper.DeleteSecretResponse
	(*GetSecretRequest)(nil),       // 12: gophkeeper.GetSecretRequest
	(*GetSecretResponse)(nil),      // 13: gophkeeper.GetSecretResponse
	(*GetListSecretsRequest)(nil),  // 14: gophkeeper.GetListSecretsRequest
	(*GetListSecretsResponse)(nil), // 15: gophkeeper.GetListSecretsResponse
}
var file_internal_pkg_proto_gophkeeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.Secret.secret_type:type_name -> gophkeeper.SecretType
	1,  // 1: gophkeeper.CreateSecretRequest.secret:type_name -> gophkeeper.Secret
	1,  // 2: gophkeeper.UpdateSecretRequest.secret:type_name -> gophkeeper.Secret
	2,  // 3: gophkeeper.LoginRequest.user:type_name -> gophkeeper.User
	3,  // 4: gophkeeper.LoginResponse.token:type_name -> gophkeeper.Token
	0,  // 5: gophkeeper.DeleteSecretRequest.secret_type:type_name -> gophkeeper.SecretType
	0,  // 6: gophkeeper.GetSecretRequest.secret_type:type_name -> gophkeeper.SecretType
	1,  // 7: gophkeeper.GetSecretResponse.secret:type_name -> gophkeeper.Secret
	0,  // 8: gophkeeper.GetListSecretsRequest.secret_type:type_name -> gophkeeper.SecretType
	1,  // 9: gophkeeper.GetListSecretsResponse.secrets:type_name -> gophkeeper.Secret
	8,  // 10: gophkeeper.GophKeeper.Register:input_type -> gophkeeper.LoginRequest
	8,  // 11: gophkeeper.GophKeeper.Login:input_type -> gophkeeper.LoginRequest
	4,  // 12: gophkeeper.GophKeeper.CreateSecret:input_type -> gophkeeper.CreateSecretRequest
	12, // 13: gophkeeper.GophKeeper.GetSecret:input_type -> gophkeeper.GetSecretRequest
	14, // 14: gophkeeper.GophKeeper.ListSecrets:input_type -> gophkeeper.GetListSecretsRequest
	6,  // 15: gophkeeper.GophKeeper.UpdateSecret:input_type -> gophkeeper.UpdateSecretRequest
	10, // 16: gophkeeper.GophKeeper.DeleteSecret:input_type -> gophkeeper.DeleteSecretRequest
	9,  // 17: gophkeeper.GophKeeper.Register:output_type -> gophkeeper.LoginResponse
	9,  // 18: gophkeeper.GophKeeper.Login:output_type -> gophkeeper.LoginResponse
	5,  // 19: gophkeeper.GophKeeper.CreateSecret:output_type -> gophkeeper.CreateSecretResponse
	13, // 20: gophkeeper.GophKeeper.GetSecret:output_type -> gophkeeper.GetSecretResponse
	15, // 21: gophkeeper.GophKeeper.ListSecrets:output_type -> gophkeeper.GetListSecretsResponse
	7,  // 22: gophkeeper.GophKeeper.UpdateSecret:output_type -> gophkeeper.UpdateSecretResponse
	11, // 23: gophkeeper.GophKeeper.DeleteSecret:output_type -> gophkeeper.DeleteSecretResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_pkg_proto_gophkeeper_proto_init() }
func file_internal_pkg_proto_gophkeeper_proto_init() {
	if File_internal_pkg_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_proto_gophkeeper_proto_rawDesc), len(file_internal_pkg_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_internal_pkg_proto_gophkeeper_proto_depIdxs,
		EnumInfos:         file_internal_pkg_proto_gophkeeper_proto_enumTypes,
		MessageInfos:      file_internal_pkg_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_internal_pkg_proto_gophkeeper_proto = out.File
	file_internal_pkg_proto_gophkeeper_proto_goTypes = nil
	file_internal_pkg_proto_gophkeeper_proto_depIdxs = nil
}
